In [1]:
import sys

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sys.path.append('../source/')
import eda as tools

# **Config**
---

In [2]:
sns.set(style="darkgrid")
pd.set_option('display.float_format', '{:,.2f}'.format)
title_data = 'Data Bulk'
paleta = sns.color_palette('Set2').as_hex()
random_seed=73

# **Data**
---

In [3]:
# --Stee data--

url_data_steel = 'https://drive.google.com/file/d/1U0EV7OV2LwnV7Cxp5Z68lxRJPvwGGSOH/view?usp=sharing'
url_data_steel = 'https://drive.google.com/uc?id=' + url_data_steel.split('/')[-2]
data_steel= pd.read_csv(url_data_steel, dtype='str')

# --Bulk--

url_data_bulk = 'https://drive.google.com/file/d/1WqFElWzLW9iGsnHfuDxZK9Wm9Y5ctK0I/view?usp=sharing'
url_data_bulk = 'https://drive.google.com/uc?id=' + url_data_bulk.split('/')[-2]
data_bulk = pd.read_csv(url_data_bulk, dtype={'key': str})

# --Gas--

url_data_gas= "hhttps://drive.google.com/file/d/12WGZjrggZ8Q-rTtX41tZPHYjH0ztZbwm/view?usp=sharing"
url_data_gas = 'https://drive.google.com/uc?id=' + url_data_gas.split('/')[-2]
data_gas = pd.read_csv(url_data_gas, dtype={'key': str})

# --Temperature--

url_data_sampling = 'https://drive.google.com/file/d/1fsV-eF3QRHKSP9HchfB73DXlcT2ZTzSE/view?usp=sharing'
url_data_sampling = 'https://drive.google.com/uc?id=' + url_data_sampling.split('/')[-2]
data_temp = pd.read_csv(url_data_sampling, dtype={'key': str})

# --Bulk Time--

url_data_bulk_time = 'https://drive.google.com/file/d/1UjtllprJ7ZcTencdpyGpI8sIcPnuBbCR/view?usp=sharing'
url_data_bulk_time = 'https://drive.google.com/uc?id=' + url_data_bulk_time.split('/')[-2]
data_bulk_time= pd.read_csv(url_data_bulk_time)

# --Wire Time--

url_data_wire= "https://drive.google.com/file/d/12LIRw-e7gahPDS63eNRW9ljLBYBXwTnK/view?usp=sharing"
url_data_wire = 'https://drive.google.com/uc?id=' + url_data_wire.split('/')[-2]
data_wire_time = pd.read_csv(url_data_wire)

# --Wire--

url_data_wire = 'https://drive.google.com/file/d/1a_KQeV-Z3l3fjM8jEQNoe2Xvez4vaOsT/view?usp=sharing'
url_data_wire = 'https://drive.google.com/uc?id=' + url_data_wire.split('/')[-2]
data_wire = pd.read_csv(url_data_wire, dtype={'key': str})

# **Feature Engineering**
---
Data Normalization columns

In [4]:
data_steel.columns = tools.normalize_name_columns(data_steel.columns)
data_bulk.columns = tools.normalize_name_columns(data_bulk.columns)
data_gas.columns = tools.normalize_name_columns(data_gas.columns)
data_temp.columns = tools.normalize_name_columns(data_temp.columns)
data_bulk_time.columns = tools.normalize_name_columns(data_bulk_time.columns)
data_wire_time.columns = tools.normalize_name_columns(data_wire_time.columns)
data_wire.columns = tools.normalize_name_columns(data_wire.columns)

**data_bulk_time**

In [5]:
data_bulk_time.head()

,key,bulk_1,bulk_2,bulk_3,bulk_4,bulk_5,bulk_6,bulk_7,bulk_8,bulk_9,bulk_10,bulk_11,bulk_12,bulk_13,bulk_14,bulk_15
0,1,NaN,NaN,NaN,2019-05-03 11:21:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 11:03:52,NaN,2019-05-03 11:03:52,2019-05-03 11:03:52
1,2,NaN,NaN,NaN,2019-05-03 11:46:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 11:40:20,NaN,2019-05-03 11:40:20,2019-05-03 11:40:20
2,3,NaN,NaN,NaN,2019-05-03 12:31:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 12:09:40,NaN,2019-05-03 12:09:40,2019-05-03 12:09:40
3,4,NaN,NaN,NaN,2019-05-03 12:48:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 12:41:24,NaN,2019-05-03 12:41:24,2019-05-03 12:41:24
4,5,NaN,NaN,NaN,2019-05-03 13:18:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 13:12:56,NaN,2019-05-03 13:12:56,2019-05-03 13:12:56

- **data_bulk_time** It will not be taken into account for the process, since it is a set of data that has the bulk delivery dates. This information no apport for target of project, Since the dates do not necessarily have an impact on the prediction of temperature

In [6]:
data_wire_time.head()

,key,wire_1,wire_2,wire_3,wire_4,wire_5,wire_6,wire_7,wire_8,wire_9
0,1,2019-05-03 11:11:41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2019-05-03 11:46:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2019-05-03 12:13:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2019-05-03 12:48:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2019-05-03 13:18:15,2019-05-03 13:32:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- **data_wire_time** It will not be taken into account for the process, since it is a set of data that has the bulk delivery dates. This information no apport for target of project, Since the dates do not necessarily have an impact on the prediction of temperature

**Data steel**

In [7]:
data_steel[[
    'active_power',
    'reactive_power'
]] = data_steel[[
    'active_power',
    'reactive_power'
]].astype("float64")

data_steel['arc_heating_start'] = pd.to_datetime(data_steel['arc_heating_start'])
data_steel['arc_heating_end'] = pd.to_datetime(data_steel['arc_heating_end'])

In [8]:
temp = np.datetime64(data_steel['arc_heating_end'][1]) - np.datetime64(data_steel['arc_heating_start'][1])
print(temp.astype('timedelta64[m]'))
print(temp / np.timedelta64(1, 'm'))

3 minutes
3.0833333333333335

In [9]:
# Calculate minutes
data_steel['minutes_process'] = data_steel.apply(lambda x: tools.calculate_time(x, 'arc_heating_start', 'arc_heating_end'), axis=1)

In [10]:
# Get month
data_steel['months'] = data_steel['arc_heating_start'].dt.month

In [11]:
data_steel.head()

,key,arc_heating_start,arc_heating_end,active_power,reactive_power,minutes_process,months
0,1,2019-05-03 11:02:14,2019-05-03 11:06:02,0.98,0.69,3.80,5
1,1,2019-05-03 11:07:28,2019-05-03 11:10:33,0.81,0.52,3.08,5
2,1,2019-05-03 11:11:44,2019-05-03 11:14:36,0.74,0.50,2.87,5
3,1,2019-05-03 11:18:14,2019-05-03 11:24:19,1.66,1.06,6.08,5
4,1,2019-05-03 11:26:09,2019-05-03 11:28:37,0.69,0.41,2.47,5

In [12]:
function_dictionary = {
    'active_power': ['sum'],
    'reactive_power': ['sum'],
    'minutes_process': ['sum']
}

new_val_col = [
    'active_power_sum',
    'reactive_power_sum',
    'minutes_process_sum'
]


data_group = data_steel.groupby([
    'key',
    'months'
]).aggregate(
    function_dictionary
)

data_group.columns = new_val_col
data_group = data_group.reset_index()

In [13]:
data_group.head()

    key  months  active_power_sum  reactive_power_sum  minutes_process_sum
0     1       5              4.88                3.18                18.30
1    10       5              2.92                2.50                13.75
2   100       5              4.44                3.15                17.72
3  1000       6              1.40                0.93                 6.75
4  1001       6              4.25                3.38                18.87

In [14]:
data_group[data_group.duplicated(subset=['key'], keep=False)]

       key  months  active_power_sum  reactive_power_sum  minutes_process_sum
708   1639       6              0.41                0.27                 2.03
709   1639       7              3.35                2.03                12.80
1504  2359       7              4.44                3.18                19.08
1505  2359       8              0.57                0.41                 2.30

This rows explain that the steel arcs were manufactured in more two month, which is seems like a mistake. the rows with less minutes of manufactured will deleted

In [15]:
data_group = data_group.sort_values(['minutes_process_sum'], ascending=False) 
data_group = data_group.drop_duplicates('key')

In [16]:
function_dictionary = {
    'active_power_sum': ['sum'],
    'reactive_power_sum': ['sum'],
    'minutes_process_sum': ['sum'],
    'months': ['count']
}

new_val_col = [
    'active_power_sum',
    'reactive_power_sum',
    'minutes_process_sum',
    'active_months'
]


data_group = data_group.groupby([
    'key',
]).aggregate(
    function_dictionary
)

data_group.columns = new_val_col
data_group = data_group.reset_index()

In [17]:
data_group.head()

,key,active_power_sum,reactive_power_sum,minutes_process_sum,active_months
0,1,4.88,3.18,18.30,1
1,10,2.92,2.50,13.75,1
2,100,4.44,3.15,17.72,1
3,1000,1.40,0.93,6.75,1
4,1001,4.25,3.38,18.87,1

In [18]:
# Copy dt Steel

data_final = data_group.copy()

In [19]:
data_final.head(1)

,key,active_power_sum,reactive_power_sum,minutes_process_sum,active_months
0,1,4.88,3.18,18.30,1

**data_bulk**

In [20]:
data_bulk = data_bulk.fillna(0)
data_bulk.head(1)

,key,bulk_1,bulk_2,bulk_3,bulk_4,bulk_5,bulk_6,bulk_7,bulk_8,bulk_9,bulk_10,bulk_11,bulk_12,bulk_13,bulk_14,bulk_15
0,1,0.00,0.00,0.00,43.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,206.00,0.00,150.00,154.00

In [21]:
data_final = data_final.merge(data_bulk, how='left')

**data_gas**

In [22]:
data_gas = data_gas.rename(columns={
    'gas_1': 'gas_purgue'
})
data_final = data_final.merge(data_gas, how='left')

**data_tempetature**

In [23]:
function_dictionary = {
    'temperature': ['sum']
}

new_val_col = [
    'temperature_sum',
]


data_group = data_temp.groupby([
    'key',
]).aggregate(
    function_dictionary
)
data_group
data_group.columns = new_val_col
data_group = data_group.reset_index()
data_group

       key  temperature_sum
0        1         8,007.00
1       10        12,678.00
2      100         6,295.00
3     1000         9,575.00
4     1001        14,293.00
...    ...              ...
3211   995         9,542.00
3212   996         7,986.00
3213   997         4,762.00
3214   998         9,482.00
3215   999         6,375.00

[3216 rows x 2 columns]

In [24]:
data_final = data_final.merge(data_group, how='left')

In [25]:
data_final.head(1)

,key,active_power_sum,reactive_power_sum,minutes_process_sum,active_months,bulk_1,bulk_2,bulk_3,bulk_4,bulk_5,...,bulk_8,bulk_9,bulk_10,bulk_11,bulk_12,bulk_13,bulk_14,bulk_15,gas_purgue,temperature_sum
0,1,4.88,3.18,18.30,1,0.00,0.00,0.00,43.00,0.00,...,0.00,0.00,0.00,0.00,206.00,0.00,150.00,154.00,29.75,"8,007.00"

**data_wire**

In [26]:
data_wire.head()

  key  wire_1  wire_2  wire_3  wire_4  wire_5  wire_6  wire_7  wire_8  wire_9
0   1   60.06     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1   2   96.05     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2   3   91.16     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
3   4   89.06     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4   5   89.24    9.11     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [27]:
data_final = data_final.merge(data_wire, how='left')

In [28]:
data_final = data_final.fillna(0)

In [29]:
data_final.head()

,key,active_power_sum,reactive_power_sum,minutes_process_sum,active_months,bulk_1,bulk_2,bulk_3,bulk_4,bulk_5,...,temperature_sum,wire_1,wire_2,wire_3,wire_4,wire_5,wire_6,wire_7,wire_8,wire_9
0,1,4.88,3.18,18.30,1,0.00,0.00,0.00,43.00,0.00,...,"8,007.00",60.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,10,2.92,2.50,13.75,1,0.00,0.00,0.00,0.00,0.00,...,"12,678.00",81.24,12.38,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,100,4.44,3.15,17.72,1,0.00,0.00,0.00,0.00,0.00,...,"6,295.00",90.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,1000,1.40,0.93,6.75,1,0.00,0.00,172.00,0.00,0.00,...,"9,575.00",169.18,24.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,1001,4.25,3.38,18.87,1,0.00,0.00,124.00,0.00,0.00,...,"14,293.00",130.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [30]:
data_final

,key,active_power_sum,reactive_power_sum,minutes_process_sum,active_months,bulk_1,bulk_2,bulk_3,bulk_4,bulk_5,...,temperature_sum,wire_1,wire_2,wire_3,wire_4,wire_5,wire_6,wire_7,wire_8,wire_9
0,1,4.88,3.18,18.30,1,0.00,0.00,0.00,43.00,0.00,...,"8,007.00",60.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,10,2.92,2.50,13.75,1,0.00,0.00,0.00,0.00,0.00,...,"12,678.00",81.24,12.38,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,100,4.44,3.15,17.72,1,0.00,0.00,0.00,0.00,0.00,...,"6,295.00",90.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,1000,1.40,0.93,6.75,1,0.00,0.00,172.00,0.00,0.00,...,"9,575.00",169.18,24.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,1001,4.25,3.38,18.87,1,0.00,0.00,124.00,0.00,0.00,...,"14,293.00",130.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3209,995,1.91,1.49,8.85,1,0.00,0.00,0.00,120.00,0.00,...,"9,542.00",129.17,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3210,996,1.19,0.90,8.23,1,0.00,0.00,0.00,174.00,0.00,...,"7,986.00",105.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3211,997,1.94,1.57,10.12,1,0.00,0.00,0.00,0.00,0.00,...,"4,762.00",51.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3212,998,2.17,1.52,9.48,1,0.00,0.00,0.00,72.00,0.00,...,"9,482.00",105.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3213,999,1.98,1.46,10.88,1,0.00,0.00,174.00,0.00,0.00,...,"6,375.00",110.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00