In [1]:
import warnings

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split
)

from sklearn.metrics import mean_absolute_error

from lazypredict.Supervised import LazyRegressor


from sklearn.ensemble import (
    GradientBoostingRegressor,
    AdaBoostRegressor,
    HistGradientBoostingRegressor,
    RandomForestRegressor)

from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    ElasticNet)

from xgboost import XGBRegressor, XGBRFRegressor

from sklearn.dummy import DummyRegressor

# **Config**
---

In [2]:
random_seed = 12354
sns.set(style="darkgrid")
sns.set(font_scale=1)
pd.set_option('display.float_format', '{:,.5f}'.format)
title_data = 'Temperature prediction'
paleta = sns.color_palette("tab10").as_hex()
warnings.filterwarnings("ignore")

To validate the initial behavior of the models that best fit, a wrapper will be used that groups default instances of regression models, which can provide an indication of how the models behave in response to data from different strategies.

LazyRegressor is used, with the mean_absolute_error metric

 However, it will be limited to the following models:

- GradientBoostingRegressor
- AdaBoostRegressor,
- HistGradientBoostingRegressor,
- RandomForestRegressor,
- LinearRegression,
- Ridge,
- ElasticNet,
- XGBRegressor,
- XGBRFRegressor
- DummyRegressor


Since LazyRegressor provides a number of models, not all of which are well-known.

In [3]:
wra_regressor = LazyRegressor(
    verbose=0,
    ignore_warnings=True, 
    custom_metric=mean_absolute_error, 
    predictions=True, 
    regressors=[
        GradientBoostingRegressor,
        AdaBoostRegressor,
        HistGradientBoostingRegressor,
        RandomForestRegressor,
        LinearRegression,
        Ridge,
        ElasticNet,
        XGBRegressor,
        XGBRFRegressor,
        DummyRegressor
        ])

# **Data First Strategy**
---

The first strategy is loaded.

In [4]:
data_first = pd.read_csv('../data/first_strategy.csv')

**Split**

In [5]:
X = data_first[[
    'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
    'gas_purgue'
]]

y = data_first['temperature_sum']

Randomly split the data into training and validation sets.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.85,
    shuffle=True,
    random_state=random_seed
)

The container is fitted with the training and validation data to adjust all the regression models offered by LazyRegressor.

In [7]:
regressor_model_first_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

100%|██████████| 10/10 [00:02<00:00,  4.31it/s]

In [8]:
regressor_model_first_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
XGBRFRegressor,0.03437,0.04238,"3,404.23463",0.10199,"2,650.15322"
GradientBoostingRegressor,0.01136,0.01957,"3,444.53929",0.42091,"2,664.34082"
AdaBoostRegressor,-0.00980,-0.00142,"3,481.21416",0.05995,"2,715.79042"
HistGradientBoostingRegressor,-0.01366,-0.00525,"3,487.86675",0.20222,"2,743.51814"
DummyRegressor,-0.01833,-0.00988,"3,495.88260",0.00841,"2,802.49959"
RandomForestRegressor,-0.07431,-0.06539,"3,590.68488",1.38185,"2,844.29414"
XGBRegressor,-0.11609,-0.10682,"3,659.83911",0.10624,"2,885.09596"
ElasticNet,-2.35962,-2.33174,"6,349.76968",0.01212,"2,924.20678"
Ridge,-25.90380,-25.68053,"17,968.82952",0.00986,"3,453.46034"
LinearRegression,-26.97378,-26.74164,"18,322.66365",0.00874,"3,469.99818"

The models typically used for linear problems have poorer performance, and their error difference is significant compared to ensemble models.

# **Data Second Strategy**
---

The second strategy is loaded.

In [9]:
data_second = pd.read_csv('../data/second_strategy.csv')

In [10]:
data_second

,key,temperature_sum,active_power_sum,reactive_power_sum,minutes_process_sum,gas_purgue,C1,C2,C3
0,1,"8,007.00000",4.87815,3.18324,18.30000,29.74999,20.66459,-39.52270,-28.69459
1,10,"12,678.00000",2.92362,2.49612,13.74900,6.52989,22.22047,-63.83044,16.63654
2,100,"6,295.00000",4.43513,3.15134,17.71700,12.64319,20.94804,-26.35074,-21.89425
3,1000,"9,575.00000",1.40241,0.93353,6.75100,9.80073,-251.22053,4.11963,158.15935
4,1001,"14,293.00000",4.24727,3.37764,18.86600,19.67891,-253.90412,-18.30161,114.97372
...,...,...,...,...,...,...,...,...,...
3209,995,"9,542.00000",1.90945,1.48719,8.85000,12.30884,-3.19796,-97.93836,-16.53886
3210,996,"7,986.00000",1.19491,0.89953,8.23300,8.83820,7.08725,-105.39740,-32.67329
3211,997,"4,762.00000",1.93813,1.56647,10.11700,7.48937,-13.82826,-46.86487,-13.20168
3212,998,"9,482.00000",2.17320,1.51996,9.48300,4.22033,-254.64611,-104.83379,5.76944
3213,999,"6,375.00000",1.97664,1.45589,10.88300,14.07026,-8.08360,36.43761,131.87718

In [11]:
X = data_second[[
    'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
    'gas_purgue', 'C1', 'C2', 'C3'
]]

y = data_second['temperature_sum']

Randomly split the data into training and validation sets.

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.85,
    shuffle=True,
    random_state=random_seed
)

In [13]:
regressor_model_second_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 10/10 [00:03<00:00,  2.82it/s]

In [14]:
regressor_model_second_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
XGBRFRegressor,0.00052,0.01504,"3,452.49277",0.12618,"2,674.30013"
RandomForestRegressor,-0.00781,0.00683,"3,466.85156",2.06517,"2,696.51344"
GradientBoostingRegressor,-0.03353,-0.01852,"3,510.81320",0.71737,"2,701.88038"
HistGradientBoostingRegressor,0.00319,0.01767,"3,447.87981",0.19939,"2,709.33345"
DummyRegressor,-0.02476,-0.00988,"3,495.88260",0.01966,"2,802.49959"
AdaBoostRegressor,-0.11383,-0.09765,"3,644.63893",0.15514,"2,808.44104"
XGBRegressor,-0.18019,-0.16305,"3,751.64318",0.22858,"2,903.63780"
ElasticNet,-2.69156,-2.63795,"6,635.15256",0.00748,"2,938.53681"
Ridge,-35.13847,-34.61364,"20,760.16160",0.01014,"3,579.58714"
LinearRegression,-36.51529,-35.97046,"21,151.93061",0.00937,"3,597.73865"

The models typically used for linear problems have poorer performance, and their error difference is significant compared to ensemble models.

# **Data Third Strategy**
---

The third strategy is loaded.

In [15]:
data_third = pd.read_csv('../data/third_strategy.csv')

In [16]:
data_third

,key,temperature_sum,C1,C2,C3,C4,C5
0,1,"8,007.00000",20.88850,-39.17555,-28.85761,29.09527,-22.80295
1,10,"12,678.00000",22.18162,-63.91922,16.61842,59.46159,-69.01695
2,100,"6,295.00000",21.03320,-26.25830,-21.93474,31.55612,-36.21207
3,1000,"9,575.00000",-251.30467,3.99810,158.15087,-53.95510,43.78298
4,1001,"14,293.00000",-253.70081,-18.05334,114.83498,-55.43850,14.96360
...,...,...,...,...,...,...,...
3209,995,"9,542.00000",-3.27465,-97.94387,-16.63067,-5.72901,50.51911
3210,996,"7,986.00000",6.96749,-105.44653,-32.75088,9.37505,77.10562
3211,997,"4,762.00000",-13.91689,-46.96295,-13.19838,-29.78941,-63.18561
3212,998,"9,482.00000",-254.73121,-104.84294,5.68684,-38.86811,15.45676
3213,999,"6,375.00000",-8.10456,36.32399,131.89901,-37.58493,12.04590

In [17]:
X = data_third[[
    "C1", "C2", "C3", "C4", "C5"
]]

y = data_third['temperature_sum']

Randomly split the data into training and validation sets.

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.85,
    shuffle=True,
    random_state=random_seed
)

In [19]:
regressor_model_third_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 10/10 [00:02<00:00,  3.41it/s]

In [20]:
regressor_model_third_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
RandomForestRegressor,0.07412,0.08372,"3,329.93804",1.69086,"2,706.52410"
GradientBoostingRegressor,0.05189,0.06172,"3,369.67689",0.56137,"2,708.60185"
HistGradientBoostingRegressor,0.05961,0.06937,"3,355.91788",0.19462,"2,711.92547"
XGBRFRegressor,0.04036,0.05031,"3,390.10122",0.13008,"2,754.34902"
ElasticNet,-0.00547,0.00496,"3,470.10898",0.00834,"2,790.95975"
Ridge,-0.00474,0.00568,"3,468.84308",0.00691,"2,793.40648"
LinearRegression,-0.00474,0.00568,"3,468.84597",0.00940,"2,793.41056"
DummyRegressor,-0.02046,-0.00988,"3,495.88260",0.00939,"2,802.49959"
XGBRegressor,-0.04429,-0.03346,"3,536.46467",0.10778,"2,817.98930"
AdaBoostRegressor,-0.24533,-0.23241,"3,861.89748",0.20855,"3,115.39417"

With the data from this strategy, the linear models show better performance.

# **Data Fourth Strategy**
---

The second strategy is loaded.

In [21]:
data_fourth = pd.read_csv('../data/fourth_strategy.csv')

In [22]:
data_fourth.columns

Index(['key', 'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
       'gas_purgue', 'temperature_sum', 'wire_1', 'bulk_12', 'bulk_14',
       'bulk_15'],
      dtype='object')

In [23]:
X = data_fourth[[
    'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
    'gas_purgue', 'wire_1', 'bulk_12', 'bulk_14',
    'bulk_15'
]]

y = data_fourth['temperature_sum']

In [24]:
X.describe()

,active_power_sum,reactive_power_sum,minutes_process_sum,gas_purgue,wire_1,bulk_12,bulk_14,bulk_15
count,"3,214.00000","3,214.00000","3,214.00000","3,214.00000","3,214.00000","3,214.00000","3,214.00000","3,214.00000"
mean,3.10283,2.09461,13.24163,11.07926,95.87360,198.55445,148.66801,112.26945
std,1.39714,12.68949,5.53983,6.18126,46.46948,152.94653,83.68066,85.39323
min,0.18623,-714.59164,0.95000,0.00000,0.00000,0.00000,0.00000,0.00000
25%,2.12634,1.59902,9.51700,7.09115,67.09716,104.00000,102.00000,0.00000
50%,2.99054,2.22893,12.82550,9.85514,99.11616,206.00000,146.00000,106.00000
75%,3.90115,2.89914,16.38300,13.80562,124.24698,260.00000,202.00000,204.00000
max,17.49650,12.58799,69.81700,77.99504,330.31442,"1,849.00000",636.00000,405.00000

Randomly split the data into training and validation sets.

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.85,
    shuffle=True,
    random_state=random_seed
)

In [26]:
regressor_model_fourth_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 10/10 [00:03<00:00,  3.18it/s]

In [27]:
y_test.mean(), y_train.mean()

(np.float64(6146.890269151138), np.float64(6492.621384108385))

The models typically used for linear problems have poorer performance, and their error difference is significant compared to ensemble models.

In [28]:
regressor_model_fourth_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
XGBRegressor,0.15062,0.16472,"3,179.34971",0.22233,"2,334.30228"
HistGradientBoostingRegressor,0.17491,0.18860,"3,133.57066",0.20893,"2,361.06766"
GradientBoostingRegressor,0.15553,0.16955,"3,170.14451",0.63459,"2,391.93725"
RandomForestRegressor,0.13653,0.15086,"3,205.61908",1.75829,"2,427.61609"
XGBRFRegressor,0.06919,0.08464,"3,328.27524",0.15584,"2,572.23009"
DummyRegressor,-0.02692,-0.00988,"3,495.88260",0.00879,"2,802.49959"
AdaBoostRegressor,-0.10563,-0.08728,"3,627.38033",0.11726,"2,852.49369"
ElasticNet,-3.26641,-3.19560,"7,125.57156",0.00944,"2,921.31957"
Ridge,-10.50697,-10.31598,"11,702.22980",0.00842,"3,129.78971"
LinearRegression,-11.08749,-10.88687,"11,993.78572",0.00909,"3,143.68888"